#!/usr/bin/env bash

: <<'END'
dhedit
DigiHub User Configuration Editor

Callsign, APRS Password, coordinates and GPS device can be changed

Version 1.0a

Steve de Bode - KQ4ZCI - December 2025

Input:	callsign
Output: none - interactive
END

