#!/usr/bin/env bash

: <<'END'
axnodepass
Genreate Random alphanumeric AX Node Password

Version 1.0a

Steve de Bode - W0FFS - December 2025

Input:	none
Output: Random AX node password
END

UI_LIB="/usr/local/lib/digihub/dh.lib"
[ -r "$UI_LIB" ] && source "$UI_LIB" || {
  printf "\nERROR: Missing UI library: %s\n\n" "$UI_LIB" >&2
  exit 1
}

axnodepass=$(openssl rand -base64 12 | tr -dc A-Za-z0-9 | head -c6)

section "AX Node Password"
kv "Password" "$axnodepass"
printf "\n"
