#!/usr/bin/env bash

: <<'END'
dhremove
DigiHub Uninstaller

Version 0.1

Steve de Bode - W0FFS - July 2026

Input:	none
Output: none - interactive
END

# Uninstallation warning 
printf '\nThis action will completely remove DigiHub, continue (Y/n)? '; read -n1 -r response
case $response in Y|y) printf '\nRemoving DigiHub.\n';; N|n) printf '\nUninstall aborted.\n\n'; exit 0 ;; *) printf '\nInvalid response, please select (Y/n)\n' ;; esac

deactivate >/dev/null 2>&1
cd "$HOME"

# Cleanup .profile
if [ -f "$HOME"/.profile.dh ]; then
 mv "$HOME"/.profile.dh "$HOME"/.profile
else
 for i in "DigiHub"  "sysinfo"; do
  if grep -qF "$i" "$HOME"/.profile; then
   sed -i "/$i/d" "$HOME"/.profile
  fi
 done
fi 

# Remove whitespace from .profile
perl -i.bak -0777 -pe 's{\s+\z}{}m' ~/.profile >/dev/null 2>&1
printf '\n' >> "$HOME"/.profile
rm "$HOME"/.profile.bak*

# Remove configuration file
 rm "$HOME"/.dhinfo*
 
# Remove Directories
sudo rm -rf $HOME/.digihub-venv

# Remove Packages

# Reboot
while true; do
 printf '\nReboot Now (Y/n) '; read -n1 -r response
 case $response in     Y|y) printf '\nRebooting\n'; break ;; N|n) printf '\nA reboot is required to completely remove DigiHub.\n\n'; break ;; *) printf '\nInvalid response, please select Y/n' ;; esac
done

