#!/usr/bin/env python3

"""
direwolfconf.py
Generate /etc/digihub/direwolf.conf for a DigiHub digital mode
(tnc, tnc300b, tracker, digipeater, node) from $HOME/.dhinfo

Version 0.1

Steve de Bode - W0FFS - July 2026

Input:  MODE (tnc|tnc300b|tracker|digipeater|node)
Output: writes /etc/digihub/direwolf.conf

Exit codes:
 0 = config written successfully
 1 = .dhinfo missing, unreadable, or callsign empty
 2 = invalid or missing MODE argument
"""

from __future__ import annotations

import os
import pwd
import sys

from audiodetect import detect_adevice

CONF_PATH = "/etc/digihub/direwolf.conf"
DHINFO_FIELDS = [
 "callsign", "class", "expiry", "grid", "lat", "lon", "licstat",
 "forename", "initial", "surname", "suffix",
 "street", "town", "state", "zip", "country",
 "aprspass", "axnodepass", "mapboxtoken",
 "winlinkpass", "defaultmode", "radiointerface",
 "rigdevice", "rigbaud", "rignumber",
 "vncpass",
]

# radiointerface -> PTT method. CM108-family USB audio adapters (including
# AIOC and most inexpensive "USB Radio Interface" dongles) expose PTT as a
# GPIO pin on the same USB Audio HID device, which Dire Wolf auto-detects
# ("PTT CM108"). DigiRig Mobile signals PTT over its USB-serial port's RTS
# line. Raspberry Pi audio HATs (Fe-Pi, DRAWS/N7NIX-style, generic "DigiPi"
# hats) wire PTT to a GPIO pin whose number depends on the exact hat and
# must be supplied by the user (stored in the rigdevice field) since it
# cannot be safely guessed.
CM108_INTERFACES = {"cm108", "aioc", "usbradio", "usbaudio", "aiz"}
RTS_INTERFACES = {"digirig"}
GPIO_INTERFACES = {"fepi", "digipihat", "drapizero"}

MODES = {"tnc", "tnc300b", "tracker", "digipeater", "node"}


def user_home() -> str:
 """Resolve the invoking (pre-sudo) user's home directory, since
 direwolfconf.py needs root to write /etc/digihub but .dhinfo lives
 under the DigiHub user's own home, not root's."""
 sudo_user = os.environ.get("SUDO_USER")
 if sudo_user and sudo_user != "root":
  try:
   return pwd.getpwnam(sudo_user).pw_dir
  except KeyError:
   pass
 return os.path.expanduser("~")


def load_dhinfo(path: str) -> dict[str, str]:
 with open(path, "r") as f:
  line = f.readline().rstrip("\n")
 fields = line.split(",")
 fields += [""] * (len(DHINFO_FIELDS) - len(fields))
 return dict(zip(DHINFO_FIELDS, fields[:len(DHINFO_FIELDS)]))


def ptt_line(radiointerface: str, rigdevice: str) -> tuple[str | None, str | None]:
 """Return (config line or None, warning or None)."""
 iface = radiointerface.strip().lower()

 if iface in CM108_INTERFACES:
  return "PTT CM108", None

 if iface in RTS_INTERFACES:
  dev = rigdevice.strip()
  if dev.startswith("/dev/"):
   return f"PTT {dev} RTS", None
  return None, (
   f'radiointerface "{radiointerface}" needs a serial device path in '
   "rigdevice (e.g. /dev/ttyUSB0); PTT left unconfigured."
  )

 if iface in GPIO_INTERFACES:
  pin = rigdevice.strip()
  if pin.isdigit():
   return f"PTT GPIO {pin}", None
  return None, (
   f'radiointerface "{radiointerface}" needs a GPIO pin number in '
   "rigdevice (see the hat's documentation); PTT left unconfigured."
  )

 return None, (
  f'Unrecognized radiointerface "{radiointerface}"; PTT left unconfigured. '
  "Set it with dhedit or dhweb."
 )


def build_conf(mode: str, info: dict[str, str]) -> tuple[str, list[str]]:
 warnings: list[str] = []
 callsign = info["callsign"].strip().upper()

 lines = [
  "# Generated by direwolfconf.py -- do not edit by hand.",
  f"# Regenerate with: direwolfconf.py {mode}",
  f"# DIGIHUB_MODE={mode}",
  "",
  f"MYCALL {callsign}",
  "",
 ]

 adevice = detect_adevice()
 if adevice:
  lines.append(f"ADEVICE {adevice}")
 else:
  warnings.append(
   "Could not confidently auto-detect the radio's audio device; using "
   "the system default. Run `arecord -l` and add an ADEVICE line to "
   f"{CONF_PATH} manually if this is wrong."
  )

 lines.append("")
 lines.append("CHANNEL 0")
 lines.append("")

 if mode == "tnc300b":
  lines.append("MODEM 300")
  lines.append("")

 pline, pwarn = ptt_line(info["radiointerface"], info["rigdevice"])
 if pline:
  lines.append(pline)
  lines.append("")
 if pwarn:
  warnings.append(pwarn)

 if mode in ("tracker", "digipeater"):
  lat, lon = info["lat"].strip(), info["lon"].strip()
  try:
   float(lat)
   float(lon)
   have_coords = True
  except ValueError:
   have_coords = False

  if have_coords:
   symbol = "digi" if mode == "digipeater" else "car"
   lines.append(
    f'PBEACON delay=1 every=10 symbol="{symbol}" '
    f'lat={lat} long={lon} comment="DigiHub {mode}"'
   )
   lines.append("")
  else:
   warnings.append(
    "No valid latitude/longitude in .dhinfo; position beaconing "
    "(PBEACON) was not configured. Set a GPS device or manual "
    "coordinates with dhedit or dhweb."
   )

 if mode == "digipeater":
  lines.append("DIGIPEAT 0 0 ^WIDE[3-7]-[1-7]$|^TEST$ ^WIDE[12]-[12]$")
  lines.append("")

 return "\n".join(lines).rstrip() + "\n", warnings


def main() -> int:
 if len(sys.argv) != 2 or sys.argv[1] not in MODES:
  sys.stderr.write(
   f"Usage: direwolfconf.py {{{'|'.join(sorted(MODES))}}}\n"
  )
  return 2

 mode = sys.argv[1]

 try:
  info = load_dhinfo(os.path.join(user_home(), ".dhinfo"))
 except OSError:
  sys.stderr.write(".dhinfo not found; run install.sh first.\n")
  return 1

 if not info["callsign"].strip():
  sys.stderr.write(".dhinfo has no callsign set.\n")
  return 1

 conf, warnings = build_conf(mode, info)

 try:
  os.makedirs(os.path.dirname(CONF_PATH), exist_ok=True)
  with open(CONF_PATH, "w") as f:
   f.write(conf)
 except OSError as e:
  sys.stderr.write(f"Could not write {CONF_PATH}: {e}\n")
  return 1

 for w in warnings:
  sys.stderr.write(f"Warning: {w}\n")

 return 0


if __name__ == "__main__":
 raise SystemExit(main())
