#!/usr/bin/env python3

"""
nodeconf.py
Generate /etc/ax25/axports, /etc/ax25/ax25d.conf, and
/etc/ax25/uronode.perms, and patch /etc/ax25/uronode.conf in place, for
DigiHub's AX.25 node/BBS ("node" mode) from $HOME/.dhinfo

Version 0.1

Steve de Bode - W0FFS - July 2026

Input:  none - reads $HOME/.dhinfo
Output: writes /etc/ax25/axports, /etc/ax25/ax25d.conf, and
        /etc/ax25/uronode.perms; patches /etc/ax25/uronode.conf in place

Exit codes:
 0 = config written successfully
 1 = .dhinfo missing, unreadable, callsign empty, or uronode not installed
"""

from __future__ import annotations

import os
import pwd
import re
import sys

DHINFO_FIELDS = [
 "callsign", "class", "expiry", "grid", "lat", "lon", "licstat",
 "forename", "initial", "surname", "suffix",
 "street", "town", "state", "zip", "country",
 "aprspass", "axnodepass", "mapboxtoken",
 "winlinkpass", "defaultmode", "radiointerface",
 "rigdevice", "rigbaud", "rignumber",
]

AXPORTS_PATH = "/etc/ax25/axports"
AX25D_CONF_PATH = "/etc/ax25/ax25d.conf"
URONODE_CONF_PATH = "/etc/ax25/uronode.conf"
URONODE_PERMS_PATH = "/etc/ax25/uronode.perms"
URONODE_EXEC = "/usr/sbin/uronode"

# Fixed port label shared by axports, kissattach's argument (see
# dhnoded(8)), and ax25d.conf's "VIA" clause -- distinct from the kernel
# network interface name the AX.25 driver assigns itself (ax0, ax1, ...),
# this is just the config-file identifier tying the three files together.
PORT_NAME = "radio"


def user_home() -> str:
 """Resolve the invoking (pre-sudo) user's home directory, since
 nodeconf.py needs root to write /etc/ax25 but .dhinfo lives under the
 DigiHub user's own home, not root's."""
 sudo_user = os.environ.get("SUDO_USER")
 if sudo_user and sudo_user != "root":
  try:
   return pwd.getpwnam(sudo_user).pw_dir
  except KeyError:
   pass
 return os.path.expanduser("~")


def load_dhinfo(path: str) -> dict[str, str]:
 with open(path, "r") as f:
  line = f.readline().rstrip("\n")
 fields = line.split(",")
 fields += [""] * (len(DHINFO_FIELDS) - len(fields))
 return dict(zip(DHINFO_FIELDS, fields[:len(DHINFO_FIELDS)]))


def build_axports(callsign: str) -> str:
 # name callsign speed paclen window description -- see axports(5).
 # speed 0: kissattach won't set a line speed, since /tmp/kisstnc is a
 # pty (Direwolf's KISS side), not a real serial TNC.
 return (
  "# Generated by nodeconf.py -- do not edit by hand.\n"
  f"{PORT_NAME} {callsign} 0 255 7 DigiHub AX.25 Node\n"
 )


def build_ax25d_conf(callsign: str) -> str:
 # See ax25d.conf(5): "[callsign VIA port]" then a catch-all entry
 # spawning uronode for any station that connects.
 return (
  "# Generated by nodeconf.py -- do not edit by hand.\n"
  f"[{callsign} VIA {PORT_NAME}]\n"
  f"default * * * * * * - root {URONODE_EXEC} uronode\n"
 )


def build_uronode_perms(axnodepass: str) -> str:
 # username type portname password permissions -- see uronode.perms(5).
 # permissions 3 = login (1) + outgoing AX.25 connects (2). Without a
 # password set, fall back to open login only (1), matching how the
 # rest of DigiHub treats an unset password as "not configured yet"
 # rather than refusing to start.
 password = axnodepass if axnodepass else "*"
 permissions = "3" if axnodepass else "1"
 return (
  "# Generated by nodeconf.py -- do not edit by hand.\n"
  f"* * * {password} {permissions}\n"
 )


def patch_directive(text: str, directive: str, value: str) -> str:
 """Replace an existing uncommented `directive ...` line with a new
 value, or append one if none is found -- uronode.conf ships with the
 package's own working defaults and help comments, which DigiHub should
 not clobber, only steer toward the operator's callsign."""
 pattern = re.compile(rf'^{re.escape(directive)}\b.*$', re.MULTILINE)
 line = f'{directive} {value}'
 if pattern.search(text):
  return pattern.sub(line, text, count=1)
 sep = "" if text.endswith("\n") else "\n"
 return f"{text}{sep}{line}\n"


def patch_uronode_conf(text: str, callsign: str) -> str:
 text = patch_directive(text, "HostName", callsign)
 text = patch_directive(text, "NodeId", callsign)
 text = patch_directive(text, "FlexID", callsign)
 return text


def main() -> int:
 try:
  info = load_dhinfo(os.path.join(user_home(), ".dhinfo"))
 except OSError:
  sys.stderr.write(".dhinfo not found; run install.sh first.\n")
  return 1

 callsign = info["callsign"].strip().upper()
 if not callsign:
  sys.stderr.write(".dhinfo has no callsign set.\n")
  return 1

 if not os.path.exists(URONODE_EXEC):
  sys.stderr.write(f"{URONODE_EXEC} not found; is uronode installed?\n")
  return 1

 try:
  os.makedirs(os.path.dirname(AXPORTS_PATH), exist_ok=True)
  with open(AXPORTS_PATH, "w") as f:
   f.write(build_axports(callsign))
  with open(AX25D_CONF_PATH, "w") as f:
   f.write(build_ax25d_conf(callsign))
  with open(URONODE_PERMS_PATH, "w") as f:
   f.write(build_uronode_perms(info["axnodepass"].strip()))
 except OSError as e:
  sys.stderr.write(f"Could not write AX.25 port config: {e}\n")
  return 1

 try:
  with open(URONODE_CONF_PATH, "r") as f:
   text = f.read()
  with open(URONODE_CONF_PATH, "w") as f:
   f.write(patch_uronode_conf(text, callsign))
 except OSError as e:
  sys.stderr.write(f"Could not update {URONODE_CONF_PATH}: {e}\n")
  return 1

 if not info["axnodepass"].strip():
  sys.stderr.write(
   "Warning: axnodepass is not set in .dhinfo; the node will allow "
   "logins without a password until you set one with dhedit or dhweb.\n"
  )

 return 0


if __name__ == "__main__":
 raise SystemExit(main())
