#!/usr/bin/env python3

"""
webchatconf.py
Generate $HOME/.config/aprsd/aprsd.conf for DigiHub's APRS WebChat
(aprsd + aprsd-webchat-extension) from $HOME/.dhinfo

Version 0.1

Steve de Bode - W0FFS - July 2026

Input:  none - reads $HOME/.dhinfo
Output: writes $HOME/.config/aprsd/aprsd.conf

Exit codes:
 0 = config written successfully
 1 = .dhinfo missing, unreadable, or callsign empty
"""

from __future__ import annotations

import os
import sys

DHINFO_FIELDS = [
 "callsign", "class", "expiry", "grid", "lat", "lon", "licstat",
 "forename", "initial", "surname", "suffix",
 "street", "town", "state", "zip", "country",
 "aprspass", "axnodepass", "mapboxtoken",
 "winlinkpass", "defaultmode", "radiointerface",
 "rigdevice", "rigbaud", "rignumber",
 "vncpass",
]

CONFIG_DIR = ".config/aprsd"
CONFIG_FILE = "aprsd.conf"

# Direwolf's default KISS-over-TCP port (see direwolfconf.py / dhdirewolf);
# every Direwolf-backed mode exposes it, so WebChat rides along on
# whichever one is active rather than needing its own radio hardware.
DIREWOLF_KISS_TCP_PORT = 8001

# The extension's own default (8001) collides with Direwolf's KISS port
# above, so it must be moved elsewhere. Doesn't collide with dhweb (8080),
# Pat (8015), ardopcf (8515/8514), or rigctld (4532).
WEBCHAT_WEB_PORT = 8888


def load_dhinfo(path: str) -> dict[str, str]:
 with open(path, "r") as f:
  line = f.readline().rstrip("\n")
 fields = line.split(",")
 fields += [""] * (len(DHINFO_FIELDS) - len(fields))
 return dict(zip(DHINFO_FIELDS, fields[:len(DHINFO_FIELDS)]))


def build_conf(info: dict[str, str], save_location: str) -> str:
 callsign = info["callsign"].strip().upper()
 lat = info["lat"].strip()
 lon = info["lon"].strip()

 lines = [
  "# Generated by webchatconf.py -- do not edit by hand.",
  "",
  "[DEFAULT]",
  f"callsign = {callsign}",
  f"owner_callsign = {callsign}",
  f"save_location = {save_location}",
 ]
 if lat and lon:
  lines.append(f"latitude = {lat}")
  lines.append(f"longitude = {lon}")
 lines += [
  "",
  "[aprs_network]",
  "# RF-only via Direwolf below; no APRS-IS/internet connection needed.",
  "enabled = false",
  "",
  "[kiss_tcp]",
  "enabled = true",
  "host = localhost",
  f"port = {DIREWOLF_KISS_TCP_PORT}",
  "",
  "[aprsd_webchat_extension]",
  "web_ip = 0.0.0.0",
  f"web_port = {WEBCHAT_WEB_PORT}",
 ]
 return "\n".join(lines).rstrip() + "\n"


def main() -> int:
 home = os.path.expanduser("~")

 try:
  info = load_dhinfo(os.path.join(home, ".dhinfo"))
 except OSError:
  sys.stderr.write(".dhinfo not found; run install.sh first.\n")
  return 1

 if not info["callsign"].strip():
  sys.stderr.write(".dhinfo has no callsign set.\n")
  return 1

 config_dir = os.path.join(home, CONFIG_DIR)
 config_path = os.path.join(config_dir, CONFIG_FILE)
 conf = build_conf(info, config_dir + "/")

 try:
  os.makedirs(config_dir, exist_ok=True)
  with open(config_path, "w") as f:
   f.write(conf)
 except OSError as e:
  sys.stderr.write(f"Could not write {config_path}: {e}\n")
  return 1

 if not (info["lat"].strip() and info["lon"].strip()):
  sys.stderr.write(
   "Warning: no latitude/longitude in .dhinfo; WebChat's GPS beacon "
   "button will be disabled until you set them with dhedit or dhweb.\n"
  )

 return 0


if __name__ == "__main__":
 raise SystemExit(main())
